version: '3'

services:
  postgres:
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'

  grafana:
    image: grafana/grafana
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - postgres
    environment:
      PGHOST: 'postgres'
      PGUSER: 'postgres'
      PGPASSWORD: 'postgres'
      PGDB: 'postgres'

  app1:
    image: vdorsonnens/pelican-sample:v1
    expose:
      - 8000
    ports:
      - 8000:8000
    links:
      - postgres
    environment:
      PGUSER: 'postgres'
      PGPASSWORD: 'postgres'
      PGHOST: 'postgres'
      PGPORT: '5432'
      PGDB: 'postgres'
  
  app2:
    image: vdorsonnens/pelican-sample:v2
    expose:
      - 8001
    ports:
      - 8001:8001
    links:
      - postgres
    environment:
      PGUSER: 'postgres'
      PGPASSWORD: 'postgres'
      PGHOST: 'postgres'
      PGPORT: '5432'
      PGDB: 'postgres'
