{
 "title": "Status codes",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status codes count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  status_code AS metric,\n  count(id) AS \"id\"\nFROM http\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1, status_code,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Error rate by version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  app_version AS metric,\n  (CASE WHEN count(id) >= lag(count(id)) OVER (PARTITION BY app_version ORDER BY $__timeGroup(\"timestamp\",$__interval)) THEN count(id) - lag(count(id)) OVER (PARTITION BY app_version ORDER BY $__timeGroup(\"timestamp\",$__interval)) WHEN lag(count(id)) OVER (PARTITION BY app_version ORDER BY $__timeGroup(\"timestamp\",$__interval)) IS NULL THEN NULL ELSE count(id) END)/extract(epoch from min(\"timestamp\") - lag(min(\"timestamp\")) OVER (PARTITION BY app_version ORDER BY $__timeGroup(\"timestamp\",$__interval))) AS \"id\"\nFROM http\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  status_code = '500'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Request count by version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  app_version AS metric,\n  count(id) AS \"id\"\nFROM http\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1, app_version,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}